### ISSUE TITLE
Server error: Capreolinae bear behaviour (incompatibility)

### ISSUE THREAD

**Issue by NiemandNatural** [kenigvovan/creaturescan_7#2]
VS 1.19.8
FotSa Capreolinae 1.1.4
Creatures and Critters (unofficial) 1.0.9

Error on server startup only occurs when Creatures and Critters is installed.
```
19.5.2024 18:19:00 [Server Error] Patch 0 (target: game:entities/land/bear.json) in capreolinae:patches/behavior_animals.json failed, following Exception was thrown:
19.5.2024 18:19:00 [Server Error] Exception: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.
   at JsonPatch.Adaptors.JsonNetTargetAdapter.AddInsertPrepend(IValueOperation operation)
   at JsonPatch.Adaptors.JsonNetTargetAdapter.AddMerge(AddMergeOperation mergeOperation)
   at JsonPatch.Adaptors.BaseTargetAdapter.ApplyOperation(Operation operation)
   at Tavis.PatchDocument.ApplyTo(IPatchTarget target)
   at Tavis.PatchDocument.ApplyTo(JToken jToken)
   at Vintagestory.ServerMods.NoObf.ModJsonPatchLoader.ApplyPatch(Int32 patchIndex, AssetLocation patchSourcefile, JsonPatch jsonPatch, Int32& applied, Int32& notFound, Int32& errorCount) in VSEssentials\Loading\JsonPatchLoader.cs:line 323
19.5.2024 18:19:00 [Server Error] Patch 3 (target: game:entities/land/bear.json) in capreolinae:patches/behavior_animals.json failed, following Exception was thrown:
19.5.2024 18:19:00 [Server Error] Exception: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.
   at JsonPatch.Adaptors.JsonNetTargetAdapter.AddInsertPrepend(IValueOperation operation)
   at JsonPatch.Adaptors.JsonNetTargetAdapter.AddMerge(AddMergeOperation mergeOperation)
   at JsonPatch.Adaptors.BaseTargetAdapter.ApplyOperation(Operation operation)
   at Tavis.PatchDocument.ApplyTo(IPatchTarget target)
   at Tavis.PatchDocument.ApplyTo(JToken jToken)
   at Vintagestory.ServerMods.NoObf.ModJsonPatchLoader.ApplyPatch(Int32 patchIndex, AssetLocation patchSourcefile, JsonPatch jsonPatch, Int32& applied, Int32& notFound, Int32& errorCount) in VSEssentials\Loading\JsonPatchLoader.cs:line 323
   ```

**Comment by kenigvovan** [comment]
tried with FotSa Capreolinae 1.1.5 on 1.19.7 and didn't get the issue,
I'll try with VS 1.19.8 but later

**Comment by NiemandNatural** [comment]
Might be a combination of C&C, FotSA Capreolinae and [Enitities Interact 1.0.8](https://mods.vintagestory.at/entitiesinteract). I got it again. :D

**Comment by NiemandNatural** [comment]
Getting rid of C&C got rid of the patching issue.
